### ISSUE TITLE
The bias_term of conv layer

### ISSUE THREAD

**Issue by weizequan** [antingshen/resnet-protofiles#10]
In your *.prototxt, the conv layer:  
weight_filler {
            type: "msra"
        }
        bias_term: false
I don't understand why set bias_term as false, which is rarely seen in the literature. 

In many cases, 
    bias_filler {
      type: "constant"
      value: 0
    }.

**Comment by antingshen** [comment]
Bias term is not needed because it's redundant with batchnorm, since batchnorm includes bias as well, and usually bias term is set to false when batchnorm is used.

(the bias term in batchnorm is the scale and bias layers that come after it)

**Comment by weizequan** [comment]
OK，i get it. Thks
