### ISSUE TITLE
Where can I find pre-trained weights files?(for caffe)

### ISSUE THREAD

**Issue by hill2hill** [antingshen/resnet-protofiles#15]
Excuse me,is there any place  I can  find a pre-trained .caffemodel  file for doing some finetuning work? 
I want to do my experiment base on resnet-101 but I can still not find a suitable weights file for caffe.
Thank you so much.

**Comment by jiaobingle** [comment]
the same question, thx!

**Comment by jiaobingle** [comment]
ok, ii fond it as below:
https://github.com/KaimingHe/deep-residual-networks

**Comment by hill2hill** [comment]
> ok, ii fond it as below:
> https://github.com/KaimingHe/deep-residual-networks

Ohhhh,thank you very much!You are so kind.
