### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by forresti** [antingshen/resnet-protofiles#2]
When training many different CNNs, I find it easier to organize the directories like this:

```
ResNet_18/train_val.prototxt
         /deploy.prototxt

ResNet_34/train_val.prototxt
         /deploy.prototxt

...etc
```

If I reorganize the code this way, would you accept such a PR?

**Comment by forresti** [comment]
P.S. I started such a refactoring here:
https://github.com/forresti/resnet-protofiles/tree/reorg_directories

**Comment by antingshen** [comment]
Sure, sounds good
