### ISSUE TITLE
iter_step in solver.prototxt

### ISSUE THREAD

**Issue by forresti** [antingshen/resnet-protofiles#3]
In the included solver.prototxt, I see: `iter_step: 2`. 

I grepped caffe-master and didn't find `iter_step` anywhere. Is this meant to be `iter_size`? Or, is something else going on?

**Comment by antingshen** [comment]
Yes, it should be `iter_size`. This is fixed on the `experiments` branch which also includes some code for fire modules, but apparently I didn't merge it :)
