### ISSUE TITLE
[Bug] resnet-50 train_val.prototxt 1st Conv Layer BlobSize mismatch

### ISSUE THREAD

**Issue by HolmesShuan** [antingshen/resnet-protofiles#5]
According to Kaiming's [caffemodel](https://github.com/KaimingHe/deep-residual-networks), the first convolutional layer of resnet-50 contains **bias_term**. Hope to fix it.

**Comment by antingshen** [comment]
We noticed this before, but does anyone know why it's there when there's already batchnorm? It's also only in resnet-50 right? 

Wonder if this is intentional on Kaiming's part. Nonetheless, I've changed it here to allow better compatibility.
