### ISSUE TITLE
Ask for resnet34.caffemodel

### ISSUE THREAD

**Issue by 408550969** [antingshen/resnet-protofiles#8]
Sorry to bother you,I trained the resnet34 on Imagenet with the shortest side is 256, but the accuracy is only 67%. I can't reach 73% of the paper. Can you share your resnet34.caffemodel? Thanks!

**Comment by antingshen** [comment]
As noted in the readme, you'll need to have additional data augmentations from the paper to get the accuracy. I don't have a caffemodel to share, but if you find one elsewhere you should be able to use it with these protofiles.

**Comment by 408550969** [comment]
Thanks!
