### ISSUE TITLE
Is there really a bias term in the first conv of resnet50?

### ISSUE THREAD

**Issue by huangh12** [antingshen/resnet-protofiles#9]
Hello,  
     Thank you very much for the protofiles. But I am curious that why you set a [bias term in the first conv](https://github.com/antingshen/resnet-protofiles/blob/master/ResNet_50_train_val.prototxt#L58) in resnet50, since it's before a bn layer. In bn layer, all the inputs will be substracted the mean and divided the variance. So it seems unnecessary to have a bias term in first conv before bn as all the others conv layers do exactly.
     :)

**Comment by huangh12** [comment]
~~Problem solved. The conv1 doesn't connect to a BN directly, while the others does. So the bias term in the first conv is ok.
Closed.~~

Wrong above.

**Comment by antingshen** [comment]
I had the same thought. Took me a while to figure out too :)

**Comment by huangh12** [comment]
Hello, 
       I find the bias term in the conv1 must be set, otherwise the official released resnet50.caffemodel can't be loaded without error. Though it's still unclear why it is necessary.

**Comment by antingshen** [comment]
Exactly, we ran into this over on #5 but we don't know why. Perhaps it's an oversight on their part, and it's actually just redundant?
